version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-task-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  
  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-task-container
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: taskuser
      DATABASE_PASSWORD: taskpassword
      DATABASE_NAME: task

volumes:
  mysql_data:
